name: .NET

on:
  push:
    branches: [ master, r_* ]
  pull_request:
    branches: [ master, r_* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create a Release
      if: github.event_name == 'push'
      env:
        BUILD_MAJOR: 0
        BUILD_MINOR: 1
        BUILD_REVISION: 0
        BUILD_PRERELEASE: ${{ github.ref == 'refs/heads/master' ? '-alpha' : '' }}
      uses: actions/create-release@v1.1.4
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: v$BUILD_MAJOR.$BUILD_MINOR.$BUILD_REVISION.$GITHUB_RUN_NUMBER$BUILD_PRERELEASE
        # The name of the release. For example, `Release v1.0.1`
        release_name: v$BUILD_MAJOR.$BUILD_MINOR.$BUILD_REVISION.$GITHUB_RUN_NUMBER$BUILD_PRERELEASE
        # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
        prerelease: github.ref == 'refs/heads/master'

